### ISSUE TITLE
installation with ZPM fails

### ISSUE THREAD

**Issue by r-cemper** [intersystems/isc-perf-ui#14]
Running Angular build script...
Building in 2 stage(s).
Running in background: npm ci --prefix C:\InterSystems\IRIS\mgr\.modules\USER\isc.perf.ui\1.0.1\ng\monlbl-viewer\ --no-progress --node-flags --max-old-space-size=8000
Der Befehl ""node"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Angular build process completed. Elapsed time: 1.048151 seconds.
Running in background: npm run --prefix C:\InterSystems\IRIS\mgr\.modules\USER\isc.perf.ui\1.0.1\ng\monlbl-viewer\ build --node-flags --max-old-space-size=8000 -- --baseHref=/csp/user/monlbl-viewer/ --progress=false
Der Befehl ""node"" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Angular build process completed. Elapsed time: 2.080767 seconds.

**Comment by r-cemper** [comment]
hint: nodejs is not mentioned as prerequisite
>>> and don't have it on my personal machine and will never have it
>>> a further argument to use docker  !!!!

**Comment by isc-tleavitt** [comment]
@r-cemper thanks for reporting. Ultimately what I'd like to be able to do is publish the built artifact to the package registry (without having artifacts in the repo - this is something all of the underlying machinery in IPM / isc.ipm.js supports except Open Exchange AFAICT).

Until then it's a documentation thing, same as reported in #2. I'll update the documentation and follow up re: the upstream issues.

**Comment by r-cemper** [comment]
I installed node.js on my ages old test box
now install works OK:
SO MY issue is closed -  Just a matter of docu.
