### ISSUE TITLE
Error on direct installation in IRIS for Windows (x86-64) 2022.1 version zpm 0.3.4

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems/isc-perf-ui#2]
zapm:ISCPERFUI>install isc.perf.ui
 
[isc.perf.ui]   Reload START (C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\)
[isc.perf.ui]   Reload SUCCESS
[isc.perf.ui]   Module object refreshed.
[isc.perf.ui]   Validate START
[isc.perf.ui]   Validate SUCCESS
[isc.perf.ui]   Compile START
WARNING: No resourceMap entry found for resource class pkg.isc.perf.ui.rest.models.LineByLineMonitor
[isc.perf.ui]   Compile SUCCESS
[isc.perf.ui]   Activate START
[isc.perf.ui]   Activate FAILURE
ERROR! File 'C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\ng\monlbl-viewer\dist\monlbl-viewer\index.html' does not exist; will not activate angular UI changes.

**Comment by timleavitt** [comment]
@SergeyMi37 what's the zpm version? (0.3.?)

**Comment by timleavitt** [comment]
Would also be helpful to have verbose output

**Comment by SergeyMi37** [comment]
zpm 0.3.4

install isc.perf.ui -v
 
Module isc.perf.ui was downloaded from registry (https://pm.community.intersystems.com)                                                                         Loading from C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\
 
Загрузка началась в 08/30/2022 06:32:43
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\module.xml как xml
Импортированный документ: isc.perf.ui.ZPM
Загрузка успешно завершена.
 
Dependencies:
isc.ipm.js 1.0.1 (installed)
isc.json 2.0.0 (installed)
isc.rest 1.1.0 (installed)
Skipping preload - directory does not exist.
Загрузка началась в 08/30/2022 06:32:43
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\module.xml как xml
Импортированный документ: isc.perf.ui.ZPM
Загрузка успешно завершена.
 
Loading isc.perf.ui in process 11052
[isc.perf.ui]   Reload START (C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\)
Skipping preload - directory does not exist.
Загрузка директории началась в 08/30/2022 06:32:43 '*'
 
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\CodeCSSGenerator.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\Installer.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\Handler.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\models\LineByLineMonitor.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\models\LineByLineMonitorConfig.cls как udl              Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\models\LineByLineMonitorMetrics.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\models\LineByLineMonitorResult.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\models\LineByLineMonitorResults.cls как udl
Загрузка файла C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\cls\pkg\isc\perf\ui\rest\models\LineByLineMonitorStatus.cls как udl
Загрузка успешно завершена.
 
[isc.perf.ui]   Reload SUCCESS
[isc.perf.ui]   Module object refreshed.
[isc.perf.ui]   Validate START
[isc.perf.ui]   Validate SUCCESS
[isc.perf.ui]   Compile START
 
Running Angular build script...
Building in 2 stage(s).
Running in background: npm ci --prefix C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\ng\monlbl-viewer\ --no-progress --node-flags --max-old-space-size=8000                                                                   "npm" ­¥ ï¢«ï¥âáï ¢­ãâà¥­­¥© ¨«¨ ¢­¥è­¥©
ª®¬ ­¤®©, ¨á¯®«­ï¥¬®© ¯à®£à ¬¬®© ¨«¨ ¯ ª¥â­ë¬ ä ©«®¬.
Angular build process completed. Elapsed time: 1.08798 seconds.
Running in background: npm run --prefix C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\ng\monlbl-viewer\ build --node-flags --max-old-space-size=8000 -- --baseHref=/csp/iscperfui/monlbl-viewer/ --progress=false
"npm" ­¥ ï¢«ï¥âáï ¢­ãâà¥­­¥© ¨«¨ ¢­¥è­¥©
ª®¬ ­¤®©, ¨á¯®«­ï¥¬®© ¯à®£à ¬¬®© ¨«¨ ¯ ª¥â­ë¬ ä ©«®¬.
Angular build process completed. Elapsed time: 2.148057 seconds.
 
Dependencies:
isc.ipm.js 1.0.1 (installed)
isc.json 2.0.0 (installed)
isc.rest 1.1.0 (installed)
Компиляция началась в 08/30/2022 06:32:46 с квалификаторами 'd-lck'
, компиляция 9 классов
Компиляция класса: pkg.isc.perf.ui.CodeCSSGenerator
Компиляция класса: pkg.isc.perf.ui.Installer
Компиляция класса: pkg.isc.perf.ui.rest.Handler
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitor
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitorConfig
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitorMetrics
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitorResult
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitorResults
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitorStatus
Компиляция программы: pkg.isc.perf.ui.CodeCSSGenerator.1
Компиляция программы: pkg.isc.perf.ui.Installer.1
Компиляция программы: pkg.isc.perf.ui.rest.Handler.1
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitor.1
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitorConfig.1
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitorMetrics.1
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitorResult.1
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitorResults.1
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitorStatus.1
WARNING: No resourceMap entry found for resource class pkg.isc.perf.ui.rest.models.LineByLineMonitor
Компиляция класса: pkg.isc.perf.ui.rest.models.LineByLineMonitor.Actions
Компиляция программы: pkg.isc.perf.ui.rest.models.LineByLineMonitor.Actions.1
Компиляция успешно завершена за 0.625 сек.
 
[isc.perf.ui]   Compile SUCCESS
[isc.perf.ui]   Activate START
[isc.perf.ui]   Activate FAILURE
ERROR! File 'C:\InterSystems\IRIS22\mgr\.modules\ISCPERFUI\isc.perf.ui\1.0.1\ng\monlbl-viewer\dist\monlbl-viewer\index.html' does not exist; will not activate angular UI changes.
zapm:ISCPERFUI>

**Comment by isc-tleavitt** [comment]
Thanks - there's a dependency on node/npm that needs to be documented. (Alternatively, could work around this by publishing an artifact with the built UI rather than just grabbing the whole git repo.)

**Comment by isc-tleavitt** [comment]
This requirement is now documented.
